name: Build hyprland_minimize

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
          name: hyprland_minimize
          path: target/release/hyprland_minimize
